version: '3'

services:
  
  db:
    container_name: postgresql
    image: postgres:16.2-bookworm
    shm_size: 128mb
    env_file: .env
    environment:
      POSTGRES_USER: sk_example_user
      POSTGRES_PASSWORD: $ROOT_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: sk_example_db
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sk_example_user"]
      interval: 10s
      timeout: 5s
      retries: 5

