spring:
  application:
    name: testTaskOneSk
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/sk_example_db
    username: sk_example_user
    password: testpass
  sql:
    init:
      mode: always
